# Generated by Django 3.2.6 on 2021-08-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePic',
        ),
    ]
