# Generated by Django 3.2.6 on 2021-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
