# Generated by Django 3.2.6 on 2021-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20210807_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.CharField(max_length=300),
        ),
    ]
